# Resolución Clase 6. Numpy. Parte 1.


<img  src="logoeica.jpeg" high=50px width=70px align="left" >

#### Construir arrays a partir de una lista simple y una lista anidada usando tipos de datos numéricos distintos para cada una


In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1,5,6,3,5,6,2])
arr1

array([1, 5, 6, 3, 5, 6, 2])

In [ ]:
arr1.dtype

dtype('int64')

In [ ]:
arr2 = np.array([1,5,6,3,5,6,2], dtype=np.int8)
arr2

array([1, 5, 6, 3, 5, 6, 2], dtype=int8)

In [ ]:
arr3 = np.array([1,5,6,3,5,6,2], dtype=np.float32)
arr3

array([1., 5., 6., 3., 5., 6., 2.], dtype=float32)

In [ ]:
arr4 = np.array([[4,8,6],[2,3,5],[7,5,7]])
arr4, arr4.dtype, arr4.ndim, arr4.shape

(array([[4, 8, 6],
        [2, 3, 5],
        [7, 5, 7]]),
 dtype('int64'),
 2,
 (3, 3))

In [ ]:
arr5 = np.array([[4,8,6],[2,3,5],[7,5,7]], dtype=np.float)
arr5, arr5.dtype

(array([[4., 8., 6.],
        [2., 3., 5.],
        [7., 5., 7.]]),
 dtype('float64'))

Construir una matriz de 4x5 a partir de: 1) listas anidadas y 2) números aleatorios

In [ ]:
np.array([[0,0,0,0,0],[1,1,1,1,1],[2,2,2,2,2],[3,3,3,3,3]])

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3]])

In [ ]:
np.random.randint(0,9,(4,5))

array([[8, 8, 5, 8, 5],
       [3, 7, 6, 5, 1],
       [7, 8, 6, 4, 8],
       [5, 1, 2, 3, 3]])

Contruir un array lineal de 36 elementos. Cambiar el shape para que tenga

- 3 filas y 12 columnas
- 4 columnas
- dimensión 4

In [ ]:
arr = np.arange(36)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [ ]:
arr.reshape((3,12))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [ ]:
arr.reshape((-1,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [ ]:
arr.reshape((2,2,3,3))

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8]],

        [[ 9, 10, 11],
         [12, 13, 14],
         [15, 16, 17]]],


       [[[18, 19, 20],
         [21, 22, 23],
         [24, 25, 26]],

        [[27, 28, 29],
         [30, 31, 32],
         [33, 34, 35]]]])

In [ ]:
arr.reshape((2,2,3,3)).ndim

4

Dado un array de enteros de shape (4, 6) seleccionar:
- El primer elemento de la primer fila
- La segunda fila
- La cuarta columna
- Los elementos mayores a 7 (u otra condición a elección)

In [ ]:
arr = np.random.randint(0,9,(4,6))
arr

array([[7, 6, 5, 3, 5, 1],
       [3, 6, 0, 4, 1, 5],
       [1, 6, 0, 1, 6, 0],
       [0, 7, 2, 4, 2, 3]])

In [ ]:
arr[0,0]

7

In [ ]:
arr[1,:]

array([3, 6, 0, 4, 1, 5])

In [ ]:
arr[:,3]

array([3, 4, 1, 4])

In [ ]:
arr[arr>7]

array([8, 8, 8, 8, 8])

Al mismo array asignarle el valor 100 al último elemento de la última fila

In [ ]:
arr[-1,-1] = 100
arr

array([[  4,   6,   4,   8,   8,   2],
       [  6,   2,   0,   0,   0,   6],
       [  2,   0,   4,   8,   5,   0],
       [  7,   8,   0,   3,   3, 100]])

Asignarle 0 a la quinta columna

In [ ]:
arr[:,4] = 0
arr

array([[  4,   6,   4,   8,   0,   2],
       [  6,   2,   0,   0,   0,   6],
       [  2,   0,   4,   8,   0,   0],
       [  7,   8,   0,   3,   0, 100]])