# Resolución Clase 6. Numpy. Parte 2.


<img  src="logoeica.jpeg" high=50px width=70px align="left" >



Calcular los cubos de los primero 15 naturales

In [1]:
import numpy as np
n = np.arange(15)
n**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744])

Sumar la matriz identidad a una matriz llena de unos

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.identity(5) + np.ones((5,5))

array([[2., 1., 1., 1., 1.],
       [1., 2., 1., 1., 1.],
       [1., 1., 2., 1., 1.],
       [1., 1., 1., 2., 1.],
       [1., 1., 1., 1., 2.]])

In [ ]:
# o bien usando broadcasting
np.identity(5) + 1

array([[2., 1., 1., 1., 1.],
       [1., 2., 1., 1., 1.],
       [1., 1., 2., 1., 1.],
       [1., 1., 1., 2., 1.],
       [1., 1., 1., 1., 2.]])

Hacer una función que calcule grados Farhenheit a partir de un array con grados Celsius

In [ ]:
def farenheit(c):
    return c*1.8 + 32

In [ ]:
farenheit(np.arange(10))

array([32. , 33.8, 35.6, 37.4, 39.2, 41. , 42.8, 44.6, 46.4, 48.2])

Hacer una función que tome dos arrays (peso y altura) y calcule el indice de masa corporal

In [ ]:
def imc(peso, altura):
    return peso/altura**2

In [ ]:
altura = np.array([1.78, 1.87, 1.60, 1.96])
peso = np.array([78, 87, 60, 96])
imc(peso,altura)

array([24.61810377, 24.8791787 , 23.4375    , 24.98958767])

Crear una matriz de  4x5 llena de ceros. Sumar 10 a la tercera columna usando broadcasting

In [ ]:
z = np.zeros((4,5))
z + np.array([0,0,10,0,0])

array([[ 0.,  0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.,  0.],
       [ 0.,  0., 10.,  0.,  0.]])

Encontrar los elementos de un array que son menores a los logaritmos al cuadrado de los elementos de otro array

In [ ]:
A = np.random.randint(1,20,(10,10))
B = np.random.randint(1,20,(10,10))
print ("Esto es A:")
print (A)
print ("Esto es B:")
print (B)
print ("Esto es C:")
C = np.log(B)**2
print (C)

Esto es A:
[[16 12 19  1 13  1 10 12  9 19]
 [ 5 17  4  1 19  3 19  9 18 12]
 [ 9 18 16 17 10  3  9  6 14 10]
 [17  2 19 15  2  6 14  6 19 19]
 [ 8 15 19  1 11  8  2  5 16 12]
 [ 8 15 15  3 10 10 13  6 14 13]
 [11  8  6 19  7 13 17 18 11 16]
 [ 3 17 17 13 10 19 19 14 13  1]
 [ 4 11  7  1  3 19 12 18  2 18]
 [17  8  8  6 16  7  4 11 18  6]]
Esto es B:
[[ 2 11 10 16  5  6 15  7 18 12]
 [ 8  4  7  8 11  9 10 14 18 12]
 [ 7  3 14 18 10  1  7  6 10 11]
 [19 10  8 10 18  4  8 10 15  2]
 [ 3 12 13  7  7 12 16 14 11  3]
 [ 1  5 12 18  3 12 12  8 17 12]
 [19 19  6 13 16 16  8 16 14 11]
 [13 10 13 11 17 16 19  4  1  7]
 [10 14  3 13 16  2  5 13  8  5]
 [10 11 11  1 10 11  6 15 18  3]]
Esto es C:
[[0.48045301 5.74990174 5.30189811 7.68724822 2.59029039 3.210402
  7.33353589 3.78656631 8.3542489  6.17476106]
 [4.32407713 1.92181206 3.78656631 4.32407713 5.74990174 4.82779584
  5.30189811 6.96462359 8.3542489  6.17476106]
 [3.78656631 1.20694896 6.96462359 8.3542489  5.30189811 0.
  3.78656631 3.21

In [ ]:
A[A < np.log(B)**2]

array([1, 1, 1, 3, 2, 2, 1, 2, 5, 3, 8, 7, 3, 1, 4, 1, 3, 2])